[versions]
tools-jackson-core-jackson-databind = "3.1.0"
org-junit-jupiter-junit-jupiter = "5.12.2"
org-junit-platform-junit-platform-launcher = "1.12.2"

[libraries]
tools-jackson-core-jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "tools-jackson-core-jackson-databind" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "org-junit-jupiter-junit-jupiter" }
org-junit-platform-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "org-junit-platform-junit-platform-launcher" }
